/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.myshopdata.view;

import com.myshopdata.controller.msdController;
import java.awt.Color;
import java.awt.Frame;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;


/**
 *
 * @author ACER
 */
public class loginView extends javax.swing.JFrame {

    /**
     * Creates new form loginView
     */
    
    msdController controller = new msdController();
    homeView home;
    

    public JPasswordField getPasword() {
        return pasword;
    }

    public JTextField getUsername() {
        return username;
    }

    
    public JTextField getNama() {
        return nama;
    }
        
        
    
    public loginView() throws SQLException {
        this.home = new homeView();
        ImageIcon img = new ImageIcon("src/com/myshopdata/img/dashboard.png");
        this.setIconImage(img.getImage());
        initComponents();
        loginView.this.getRootPane().setBorder(new LineBorder(Color.yellow));
        
        
    }
    int xx, xy;
    String Username = "admin";
    String Pass = "admin";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bg = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        barpanel = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        minimalize = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        txtusername = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        txtpass = new javax.swing.JLabel();
        pasword = new javax.swing.JPasswordField();
        btnsignin = new keeptoo.KButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txtsign = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        txtnama = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        iconmsd = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setForeground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(1080, 690));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(209, 216, 224));
        jLabel1.setText("Selamat Datang");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(209, 216, 224));
        jLabel2.setText("Silahkan Sign in Untuk Melanjutkan");

        jSeparator1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(100, 10));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(209, 216, 224));
        jLabel3.setText("Di ");

        barpanel.setOpaque(false);
        barpanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barpanelMouseDragged(evt);
            }
        });
        barpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barpanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barpanelMousePressed(evt);
            }
        });

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myshopdata/img/clear-button.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        minimalize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myshopdata/img/minimize.png"))); // NOI18N
        minimalize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minimalizeMousePressed(evt);
            }
        });

        javax.swing.GroupLayout barpanelLayout = new javax.swing.GroupLayout(barpanel);
        barpanel.setLayout(barpanelLayout);
        barpanelLayout.setHorizontalGroup(
            barpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barpanelLayout.createSequentialGroup()
                .addGap(750, 750, 750)
                .addComponent(minimalize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        barpanelLayout.setVerticalGroup(
            barpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(barpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exit)
                    .addComponent(minimalize))
                .addContainerGap())
        );

        loginPanel.setBackground(new java.awt.Color(209, 216, 224));

        txtusername.setBackground(new java.awt.Color(0, 0, 0));
        txtusername.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtusername.setText("Username");

        username.setBackground(new java.awt.Color(209, 216, 224));
        username.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        username.setBorder(null);

        txtpass.setBackground(new java.awt.Color(0, 0, 0));
        txtpass.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtpass.setText("Password");

        pasword.setBackground(new java.awt.Color(209, 216, 224));
        pasword.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        pasword.setBorder(null);

        btnsignin.setBorder(null);
        btnsignin.setText("Sign In");
        btnsignin.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnsignin.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnsignin.setkBorderRadius(50);
        btnsignin.setkEndColor(new java.awt.Color(0, 51, 255));
        btnsignin.setkFillButton(false);
        btnsignin.setkForeGround(new java.awt.Color(0, 0, 0));
        btnsignin.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        btnsignin.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnsignin.setkHoverStartColor(new java.awt.Color(0, 51, 255));
        btnsignin.setkStartColor(new java.awt.Color(255, 0, 255));
        btnsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsigninActionPerformed(evt);
            }
        });

        txtsign.setBackground(new java.awt.Color(0, 0, 0));
        txtsign.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtsign.setText("Sign In");

        icon.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myshopdata/img/round-account.png"))); // NOI18N

        txtnama.setBackground(new java.awt.Color(0, 0, 0));
        txtnama.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtnama.setText("Nama");

        nama.setBackground(new java.awt.Color(209, 216, 224));
        nama.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nama.setBorder(null);

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon)
                    .addComponent(txtsign))
                .addGap(157, 157, 157))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pasword, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addComponent(username)
                    .addComponent(nama)
                    .addComponent(txtnama, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpass, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtusername, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnsignin, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtsign)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtnama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtusername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pasword, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnsignin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );

        iconmsd.setBackground(new java.awt.Color(255, 255, 255));
        iconmsd.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        iconmsd.setForeground(new java.awt.Color(209, 216, 224));
        iconmsd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myshopdata/img/msd.png"))); // NOI18N

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iconmsd))
                            .addComponent(jLabel2)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(barpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(barpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(iconmsd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 861, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsigninActionPerformed
        
        
        if (username.getText().trim().equals("admin") && (pasword.getText().trim().equals("admin"))) {
            controller.btnSignIn(home);
            this.setVisible(false);
        } else {
                JOptionPane.showMessageDialog(null, "Username / pass anda salah");
        }
        
        
        
           
    }//GEN-LAST:event_btnsigninActionPerformed

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    private void barpanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barpanelMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_barpanelMousePressed

    private void barpanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barpanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_barpanelMouseDragged

    private void barpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barpanelMouseClicked
         if (evt.getClickCount() == 2 &&!evt.isConsumed()) 
         {
             if (loginView.this.getExtendedState()==MAXIMIZED_BOTH) 
             {
                 loginView.this.setExtendedState(JFrame.NORMAL);
             } 
             else 
             {
                 loginView.this.setExtendedState(WIDTH);
             }
        }
    }//GEN-LAST:event_barpanelMouseClicked

    private void minimalizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimalizeMousePressed
        loginView.this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimalizeMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new loginView().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(loginView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barpanel;
    private keeptoo.KGradientPanel bg;
    private keeptoo.KButton btnsignin;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel iconmsd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel minimalize;
    public javax.swing.JTextField nama;
    private javax.swing.JPasswordField pasword;
    private javax.swing.JLabel txtnama;
    private javax.swing.JLabel txtpass;
    private javax.swing.JLabel txtsign;
    private javax.swing.JLabel txtusername;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

}
